export const SoftSkills = {
  softSkills: {
    Communication: [
      'Verbal Communication',
      'Written Communication',
      'Active Listening',
      'Public Speaking',
      'Presentation Skills',
      'Non-verbal Communication',
    ],
    TeamworkCollaboration: [
      'Team Player',
      'Conflict Resolution',
      'Interpersonal Skills',
      'Cross-functional Collaboration',
      'Giving and Receiving Feedback',
    ],
    ProblemSolvingCriticalThinking: [
      'Analytical Thinking',
      'Creativity',
      'Decision Making',
      'Logical Reasoning',
      'Research Skills',
      'Troubleshooting',
    ],
    LeadershipsManagement: [
      'Leadership',
      'Mentoring',
      'Delegation',
      'Motivating Others',
      'Project Management',
      'Strategic Thinking',
    ],
    WorkEthicResponsibility: [
      'Time Management',
      'Accountability',
      'Reliability',
      'Discipline',
      'Commitment',
      'Professionalism',
    ],
    AdaptabilityFlexibility: [
      'Resilience',
      'Open-mindedness',
      'Stress Management',
      'Curiosity',
      'Willingness to Learn',
      'Ability to Handle Change',
    ],
    EmotionalIntelligence: [
      'Self-awareness',
      'Self-regulation',
      'Empathy',
      'Social Skills',
      'Motivation',
      'Positive Attitude',
    ],
    OrganizationalSkills: [
      'Planning',
      'Prioritization',
      'Goal Setting',
      'Multitasking',
      'Attention to Detail',
      'Resource Management',
    ],
  },
};

export const TechSkills = {
  technologySkills: {
    ProgrammingLanguages: [
      'JavaScript',
      'TypeScript',
      'Python',
      'Java',
      'C#',
      'C++',
      'Go',
      'Ruby',
      'PHP',
      'Rust',
    ],
    FrontendTechnologies: [
      'React',
      'Angular',
      'Vue.js',
      'Svelte',
      'Next.js',
      'Tailwind CSS',
      'Bootstrap',
      'HTML5',
      'CSS3',
    ],
    BackendTechnologies: [
      'Node.js',
      'Express.js',
      'Django',
      'Flask',
      'Spring Boot',
      'ASP.NET Core',
      'Laravel',
      'FastAPI',
      'Ruby on Rails',
    ],
    Databases: [
      'MySQL',
      'PostgreSQL',
      'MongoDB',
      'SQLite',
      'Redis',
      'Oracle',
      'Microsoft SQL Server',
      'Cassandra',
    ],
    DevOpsTools: [
      'Docker',
      'Kubernetes',
      'Git',
      'GitHub',
      'GitLab',
      'CI/CD',
      'Jenkins',
      'Terraform',
      'Ansible',
    ],
    CloudPlatforms: [
      'AWS',
      'Azure',
      'Google Cloud Platform',
      'Firebase',
      'Heroku',
      'Netlify',
      'Vercel',
    ],
    MobileDevelopment: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Android SDK', 'iOS SDK'],
    DataAI: [
      'Pandas',
      'NumPy',
      'TensorFlow',
      'PyTorch',
      'Scikit-learn',
      'Keras',
      'OpenCV',
      'Jupyter Notebook',
    ],
    OtherToolsTechnologies: [
      'Webpack',
      'Vite',
      'Babel',
      'ESLint',
      'Prettier',
      'Figma',
      'Postman',
      'GraphQL',
      'REST APIs',
    ],
  },
};
